Week-1
Dev-incubator/DIMS.UI-14 pull request #10
Opened 2021-04-22 10:39 UTC by Dev1LtJ

Added Users & Tasks pages. After DI call project was refactored: Users, User, Tasks & Task became a class components, what should improve performance coz of reduce quantity of rendering.

The main goal of PR is to confirm of chosen way of data structure disctribution.

2021-04-24 22:07 UTC, maximsan requested changes
Hello! I really don't see any benefit of using dispatch as you did.  Anyway I left some comments, let me know it something unclear. Please review, fix them and answer to all my notes.  Thanks!

2021-04-24 22:07 UTC, maximsan commented on src/pages/Tasks.jsx
> +      return <Task dispatch={this.dispatch} key={task.id.toString()} taskData={task} tableIndex={index + 1} />;
no need to use `toString()`

2021-04-24 22:07 UTC, maximsan commented on src/pages/Users.jsx
> +          age: 43,
extract static data

2021-04-24 22:07 UTC, maximsan commented on src/utilities/ActionCreators.js
> +    this.lastCallTimer = setTimeout(() => func(args), time);
should be extracted in separate file and covered with unit tests

2021-04-24 22:07 UTC, maximsan commented on src/pages/Users.jsx
> +          selectedModal: action.modalType,
if you want to use dispatch what the sense to use the same code in several components ? It doesn't apply any benefit

2021-04-24 22:07 UTC, maximsan commented on src/pages/Users.jsx
> +          usersList: prevState.usersList.filter((item) => item.id !== action.selectedID),
if you want to use dispatch what the sense to use the same code in several components ? It doesn't apply any benefit

2021-04-24 22:07 UTC, maximsan commented on src/pages/Tasks.jsx
> +          tasksList: prevState.tasksList.filter((item) => item.id !== action.selectedID),
You have the same code in several places, think how to avoid repetitive code

2021-04-24 22:07 UTC, maximsan commented on src/components/User/User.jsx
> +          selectedModal: action.modalType,
You have the same code in several places, think how to avoid repetitive code

2021-04-24 22:07 UTC, maximsan commented on src/components/Task/Task.jsx
> +          selectedModal: action.modalType,
You have the same code in several places, think how to avoid repetitive code

2021-04-25 08:34 UTC, Dev1LtJ commented on src/App/App.jsx
> +        break;
Yes, now it is. I just leave it and the component state in this specific form (object inside object inside object) for the possible new functionality since i transfer state to the components on the lower level. Maybe, with SPA growth i will add some another cases and state fields. If no, I will simplify it, of course. Anyway, if you want, i can refactor it right now to the usual function. Let me know, please.

2021-04-25 08:43 UTC, Dev1LtJ commented on src/components/Aside/Aside.jsx
> +  menu: PropType.instanceOf(Object).isRequired,
Thx, fixed.
```suggestion
Aside.propTypes = {
  menu: PropType.shape({ isOpen: PropType.bool }).isRequired,
};
```

2021-04-25 08:50 UTC, Dev1LtJ commented on src/components/Aside/Menu/Menu.jsx
> +    return <MenuItem key={index.toString()} title={item.title} path={item.path} image={item.image} />;
Yes, you are right, i know it too. I temporarily use index as a keys, until a don't fully connect firebase to my project. Later i will replace them for a database unique keys.

P.S. toString is needed to solve airbnb's linter check ("Do not use Array index in keys  react/no-array-index-key").

2021-04-25 08:59 UTC, Dev1LtJ commented on src/components/Main/Main.jsx
> +        <Route path='/users' render={() => <Users />} />
Fixed. Right?
```suggestion
        <Route path='/users' component={Users} />
        <Route path='/tasks' component={Tasks} />
```

2021-04-25 09:13 UTC, Dev1LtJ commented on src/components/Main/Header/Header.jsx
> +  menu: PropType.instanceOf(Object).isRequired,
I replace it for only one prop downstreaming, which i need.
```suggestion
Header.propTypes = {
  dispatch: PropType.func.isRequired,
  isOpen: PropType.bool.isRequired,
};
```

2021-04-25 09:15 UTC, Dev1LtJ commented on src/components/Main/Main.jsx
> +        <Route path='/tasks' render={() => <Tasks />} />
Fixed. Right?
```suggestion
        <Route path='/users' component={Users} />
        <Route path='/tasks' component={Tasks} />
```

2021-04-25 09:20 UTC, Dev1LtJ commented on src/components/Modals/Modal.jsx
> +  settings: PropType.instanceOf(Object).isRequired,
Fixed it only for settings, coz item, as you can see, is a specific object, contains fields, differs depending on item (task or user, or something else).
```suggestion
Modal.propTypes = {
  item: PropType.instanceOf(Object),
  dispatch: PropType.func.isRequired,
  settings: PropType.shape({ isOpen: PropType.bool, selectedModal: PropType.string }).isRequired,
};
```

2021-04-25 09:37 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +            validatorField = Boolean(action.body.match(/[a-z]{2,}/gi));
Completed! regExp-helpers.js has been created. 
```suggestion
            validatorField = regExpNamesCheck(action.body);
```

2021-04-25 09:41 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +            validatorField = Boolean(action.body.match(/[-.\w]+@([\w-]+\.)+[\w-]+/g));
Completed! regExp-helpers.js has been created.
```suggestion
            validatorField = regExpEmailCheck(action.body);
```

2021-04-25 09:44 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +              action.body.match(/(?=.*[0-9])(?=.*[-_!@#$%^&*])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*_-]{8,}/g),
Completed.
```suggestion
              validatorField = regExpPasswordCheck(action.body);
```

2021-04-25 09:48 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +            validatorField = new Date().getFullYear() - new Date(action.body).getFullYear() >= 18;
Completed.
```suggestion
            validatorField = dateOfBirthCheck(action.body);
```

2021-04-25 09:51 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +            validatorField = Boolean(action.body.match(/^(\+375)(29|25|44|33)(\d{3})(\d{2})(\d{2})$/));
Completed.
```suggestion
            validatorField = regExpPhoneCheck(action.body);
```

2021-04-25 09:53 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +            validatorField = Boolean(action.body.match(/^\d{1}(\.\d{1})?$/));
Completed:
```suggestion
            validatorField = regExpScoreCheck(action.body);
```

2021-04-25 09:57 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +          <Button onClick={() => {}} roleclass='create'>
Fixed! Btw, can u explain me, why we can't use ()=> {} metod stub, and need to use noop instead?
```suggestion
          <Button onClick={noop} roleclass='create'>
            Create
          </Button>
```

2021-04-25 09:59 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +          <Button onClick={closeUserCreateModal}>Close</Button>
OK:)
```suggestion
          <Button onClick={closeModal}>Close</Button>
```

2021-04-25 10:01 UTC, Dev1LtJ commented on src/components/Modals/Users/Validator.jsx
> +  if (error.length > 0) {
Thx, fixed.
```suggestion
  export default function Validator({ error }) {
      return error.length ? <div className={classes.validator}>{error}</div> : null;
  }
```

2021-04-25 10:01 UTC, Dev1LtJ commented on src/components/Modals/Users/Validator.jsx
> +  return null;
Thx, fixed.
```suggestion
  export default function Validator({ error }) {
      return error.length ? <div className={classes.validator}>{error}</div> : null;
  }
```

2021-04-25 10:03 UTC, Dev1LtJ commented on src/components/Task/Task.jsx
> +            <Button roleclass='edit' onClick={() => {}}>
Fixed. Btw, can u explain me, why we can't use ()=> {} metod stub, and need to use noop instead?
```suggestion
            <Button roleclass='edit' onClick={noop}>
              Edit
            </Button>
```

2021-04-25 10:04 UTC, Dev1LtJ commented on src/pages/Tasks.jsx
> +        },
I will delete it very soon (when fully connect firebase to my project).

2021-04-25 10:07 UTC, Dev1LtJ commented on src/pages/Tasks.jsx
> +        break;
Yes, now it is. I just leave it for new functionality. Look at Users.jsx as example.

2021-04-25 10:07 UTC, Dev1LtJ commented on src/pages/Tasks.jsx
> +      return <Task dispatch={this.dispatch} key={task.id.toString()} taskData={task} tableIndex={index + 1} />;
Yes, you are right, i know it too. I temporarily use index as a keys, until a don't fully connect firebase to my project. Later i will replace them for a database unique keys.

P.S. toString is needed to solve airbnb's linter check ("Do not use Array index in keys react/no-array-index-key").

2021-04-25 10:07 UTC, Dev1LtJ commented on src/pages/Users.jsx
> +          age: 43,
I will delete it very soon (when fully connect firebase to my project).

2021-04-25 10:36 UTC, Dev1LtJ commented on src/utilities/ActionCreators.js
> +    this.lastCallTimer = setTimeout(() => func(args), time);
Extracted to /utilities/debounce.js. But i don't know how to do unit tests.... Need to read...

2021-04-25 16:52 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                    type='text'
I created my own input component:
`
const CraftInput = ({ id, type, title, isRequired, onChange, readOnly, value, error, options })
`

2021-04-25 16:52 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                  </select>
I created my own input component:
`
const CraftInput = ({ id, type, title, isRequired, onChange, readOnly, value, error, options })
`

2021-04-25 16:52 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                    onChange={eventMakerAndValidator}
I created my own input component:
`
const CraftInput = ({ id, type, title, isRequired, onChange, readOnly, value, error, options })
`

2021-04-25 16:52 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                    onChange={eventMakerAndValidator}
I created my own input component:
`
const CraftInput = ({ id, type, title, isRequired, onChange, readOnly, value, error, options })
`

2021-04-25 18:22 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +        }
Ok! I created form-validators.js and moved this logic there. Now:
```suggestion
  dispatch(action) {
    const { validator } = this.state;
    const { dispatch } = this.props;
    switch (action.type) {
      case USERS_MODAL:
        dispatch(closeAnyUsersModal());
        break;
      case CREATE_USER_ONCHANGE:
        this.setState((prevState) => ({
          ...prevState,
          data: {
            ...prevState.data,
            [action.name]: action.body,
          },
        }));
        if (action.name in validator) {
          const { name, validity, errorMsg } = validateInput(action.name, action.body);
          this.setState((prevState) => ({
            ...prevState,
            validator: {
              ...prevState.validator,
              [name]: validity,
            },
            errors: {
              ...prevState.errors,
              [`${name}Error`]: errorMsg,
            },
          }));
        }
        break;
      default:
        break;
    }
  }
```

2021-04-25 18:23 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                    onChange={eventMakerAndValidator}
Fixed! Now i have just one function:
```suggestion
    const handleClick = (event) => {
      this.dispatch(createUserHandleInputChange(event));
    };
```

2021-04-25 19:16 UTC, Dev1LtJ commented on src/pages/Users.jsx
> +          selectedModal: action.modalType,
Good advice, but difficult for solve! Right? 
```suggestion
switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };
      return state;
    default:
      return prevState;
 }
```

2021-04-25 19:16 UTC, Dev1LtJ commented on src/components/User/User.jsx
> +          selectedModal: action.modalType,
Good advice, but difficult for solve! Right? 
```suggestion
switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };
      return state;
    default:
      return prevState;
 }
```

2021-04-25 19:17 UTC, Dev1LtJ commented on src/components/Task/Task.jsx
> +          selectedModal: action.modalType,
Good advice, but difficult for solve! Right? 
```suggestion
switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };
      return state;
    default:
      return prevState;
 }
```

2021-04-25 19:22 UTC, Dev1LtJ commented on src/pages/Users.jsx
> +          selectedModal: action.modalType,
Good advice, but difficult for solve! Right? 
```suggestion
  switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
    case USERS_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };

      return state;
    default:
      return prevState;
  }
```

2021-04-25 19:32 UTC, Dev1LtJ commented on src/pages/Users.jsx
> +          usersList: prevState.usersList.filter((item) => item.id !== action.selectedID),
Good advice, but difficult for solve! Right? 
```suggestion
  switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
    case USERS_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };
      return state;
    case DELETE_USER:
      state = {
        ...prevState,
        usersList: prevState.usersList.filter((item) => item.id !== action.selectedID),
      };
      return state;
    case DELETE_TASK:
      state = {
        ...prevState,
        tasksList: prevState.tasksList.filter((item) => item.id !== action.selectedID),
      };
      return state;
    default:
      return prevState;
  }
```

2021-04-25 19:32 UTC, Dev1LtJ commented on src/pages/Tasks.jsx
> +          tasksList: prevState.tasksList.filter((item) => item.id !== action.selectedID),
Good advice, but difficult for solve! Right? 
```suggestion
  switch (action.type) {
    case USER_MODAL:
    case TASK_MODAL:
    case USERS_MODAL:
      state = {
        ...prevState,
        isOpen: !prevState.isOpen,
        selectedModal: action.modalType,
      };
      return state;
    case DELETE_USER:
      state = {
        ...prevState,
        usersList: prevState.usersList.filter((item) => item.id !== action.selectedID),
      };
      return state;
    case DELETE_TASK:
      state = {
        ...prevState,
        tasksList: prevState.tasksList.filter((item) => item.id !== action.selectedID),
      };
      return state;
    default:
      return prevState;
  }
```

2021-04-29 17:46 UTC, maximsan commented on src/App/App.jsx
> +        break;
Don't think about the future cases. They can happen or not. You should think about your current task. You can rewrite and add other cases/methods etc. later.

2021-04-29 18:01 UTC, maximsan approved these changes
Looks fine. It's approved.

2021-04-29 18:01 UTC, maximsan commented on src/utilities/regExp-helpers.js
> +  return currentYear - new Date(str).getFullYear() >= 18;
add unit-tests

2021-04-30 08:46 UTC, YauhenKoipish approved these changes

2021-04-30 23:50 UTC, Dev1LtJ commented on src/App/App.jsx
> +        break;
Ok, got it.

2021-04-30 23:53 UTC, merged