Week 2
Dev-incubator/DIMS.UI-14 pull request #14
Opened 2021-05-02 19:04 UTC by Dev1LtJ

Added add task function with users selection. Also added show task function.

2021-05-05 21:28 UTC, maximsan requested changes
Hello! I left notes and highlight places that should be improved. I do not repeat the same everywhere. It means you should apply the same recommendations in other places where you have the same issues. Tests look fine.

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +const newTaskRef = createElemRef(TASKS);
in this case it can be inside class component in constructor

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +export default class CreateTask extends React.Component {
you can use `PureComponent` here

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +      .then((querySnapshot) => {
`52-53` should be in the service method

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +        return usersList;
write in 1 row with `reduce` if you can

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const { name, value } = target;
do `spread in 1 row` if you can

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const targetType = target.type;
no need to do this, spread it in upper row

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +    actFunc(newTaskRef, newTask);
could you name it more properly? it's not clear from name what this `act` actually means

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const handleChange = (event) => this.onChange(event);
move it outside the render

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +              type='date'
can you create some kind or DateInput and do not repeat type `date` several times ?

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +            <Button onClick={this.liftUpCreateTask} roleclass='create' disabled={!isValid}>
`roleclass` must be `roleClass` according to naming convention

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.module.css
> +  transform: translate(-50%, -50%);
you can do this with `flexbox` only i believe

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.module.css
> +  line-height: 25px;
use `rem` because it's responsive value

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.module.css
> +  margin-top: 30px;
use rem because it's responsive value

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/EditTask.jsx
> +export default class EditTask extends React.Component {
use `PureComponent`

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/EditTask.jsx
> +      type: CREATE_TASK_VALIDATE_FIELDS,
it should be named like `EDIT_TASK_VALIDATE_FIELDS` according to your approach

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/Task-helpers.js
> +              selectedUsers: newSelectedUsers,
can be reduced to `selectedUsers` only

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Tasks/Task-helpers.js
> +        const validity = Boolean(prevState.data.selectedUsers.length);
you can use just `!!`

2021-05-05 21:28 UTC, maximsan commented on src/components/Modals/Users/EditUser.jsx
> +    const editUser = () => this.liftUpEditUser();
move outside `render`

2021-05-05 21:28 UTC, maximsan commented on src/utilities/internationalization.js
> +export const intDate = (date) => new Intl.DateTimeFormat('ru').format(new Date(date));
why is it named so strange ? give it a clear name please

2021-05-06 20:43 UTC, Dev1LtJ commented on src/components/DivAnchor.jsx
> +  );
It's looks like role and tabIndex must be hardcoded.

`Line 8:5:  Static HTML elements with event handlers require a role  jsx-a11y/no-static-element-interactions`

```suggestion
export default function DivAnchor({ children, onClick, ...rest }) {
  const { role, tabIndex, ...restProps } = rest;
  return (
    <div className={classes.anchor} role={role} tabIndex={tabIndex} onKeyDown={noop} onClick={onClick} {...restProps}>
      {children}
    </div>
  );
}

DivAnchor.propTypes = {
  onClick: PropTypes.func.isRequired,
  children: PropTypes.node.isRequired,
  role: PropTypes.string,
  tabIndex: PropTypes.number,
};

DivAnchor.defaultProps = {
  role: 'button',
  tabIndex: 0,
};
```

2021-05-06 20:56 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const { name, value } = target;
Dont in 1 row. Thx linter :D
```suggestion
    const {
      target,
      target: { name, value },
    } = event;
```

2021-05-06 21:00 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const targetType = target.type;
Good idea! Done:
```suggestion
    const {
      target: { name, value, type: targetType },
    } = event;
```

2021-05-06 21:11 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +    actFunc(newTaskRef, newTask);
I have default agreement, that all modals can take 2 functions: actFunc (depends on what modal do) and closeFunc (as follows from name - close modal). In this case actFunc means "Life up create user action" to dispatch it to DB from common page "TASKS". I can name it by this way:
`    case TASK_MODAL_EDIT_TASK:
      modal = <EditTask task={item} closeFunc={closeFunc} liftUpCreateUser={actFunc} />;
      break;`
```suggestion
  liftUpCreateTask() {
    const { liftUpCreateUser } = this.props;
    const { data } = this.state;
    const newTask = { ...data };
    liftUpCreateUser(newTaskRef, newTask);
    this.closeModal();
  }
```

2021-05-06 21:19 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +    const handleChange = (event) => this.onChange(event);
Hmmm, seems like i don't need that function at all. I can pass `this.onChange` to components directly.
`            <CraftInput title='Title' isRequired id='title' value={title} onChange={this.onChange} error={titleError} />`

2021-05-06 21:26 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.module.css
> +  transform: translate(-50%, -50%);
Yup!
```suggestion
.modal {
  width: 30%;
  background-color: var(--white-color);
  padding: 30px;
  border: 1px solid var(--lightgray-color);
  border-radius: 20px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  box-shadow: 0 0 2px 0 var(--lightgray-color);
}
```

2021-05-06 21:32 UTC, Dev1LtJ commented on src/components/Modals/Tasks/EditTask.jsx
> +      type: CREATE_TASK_VALIDATE_FIELDS,
Yes! Fixed.
``
```suggestion
  validateFields(fieldName, fieldValue, targetType) {
    const state = reducerFunc(this.state, {
      type: EDIT_TASK_VALIDATE_FIELDS,
      fieldName,
      fieldValue,
      targetType,
    });
    this.setState(state, this.validateForm);
  }
```

2021-05-06 21:35 UTC, Dev1LtJ commented on src/components/Modals/Tasks/Task-helpers.js
> +        const validity = Boolean(prevState.data.selectedUsers.length);
Optimization:
```suggestion
        const validity = !!prevState.data.selectedUsers.length;
```

2021-05-06 21:40 UTC, Dev1LtJ commented on src/components/Modals/Users/EditUser.jsx
> +    const editUser = () => this.liftUpEditUser();
Hmmm, seems like i don't need that function at all. I can pass this.liftUpEditUser to components directly.
`          <Button onClick={this.liftUpEditUser} roleclass='edit' disabled={!isValid}>
            Edit
          </Button>`

2021-05-06 21:43 UTC, Dev1LtJ commented on src/utilities/internationalization.js
> +export const intDate = (date) => new Intl.DateTimeFormat('ru').format(new Date(date));
It means internationalizedDate:
```suggestion
export const internationalizedDate = (date) => new Intl.DateTimeFormat('ru').format(new Date(date));
```

2021-05-06 21:49 UTC, Dev1LtJ commented on src/components/Modals/Tasks/EditTask.jsx
> +export default class EditTask extends React.Component {
```suggestion
export default class EditTask extends React.PureComponent
```

2021-05-06 21:53 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +            <Button onClick={this.liftUpCreateTask} roleclass='create' disabled={!isValid}>
Fixed.
```suggestion
            <Button onClick={this.liftUpCreateTask} roleClass='create' disabled={!isValid}>
              Create
            </Button>
```

2021-05-07 07:21 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +export default class CreateTask extends React.Component {
Fixed.
```suggestion
export default class CreateTask extends React.PureComponent
```

2021-05-07 07:32 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +        return usersList;
I reworked this method in Week-3 branch in order to optimization of internet requests. Now usersList calls in TASKS page and downstreams to ShowTask, EditTask and CreateTask modals.

2021-05-07 07:35 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +              type='date'
I can, ofc. I think it is easier to pass type as prop to fully configured component instead of creating new, especially if they work similar.

2021-05-07 07:39 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +      .then((querySnapshot) => {
Reworked:
```suggestion
  componentDidMount() {
    getCollection(USERS)
      .then((querySnapshot) => {
```

2021-05-07 07:41 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +const newTaskRef = createElemRef(TASKS);
Reworked.

```suggestion
      data: {
        title: '',
        description: '',
        startDate: '',
        deadLine: '',
        selectedUsers: [],
        id: createElemRef(TASKS),
      },
```

2021-05-07 08:01 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.module.css
> +  line-height: 25px;
Good idea! Reworked:
```suggestion
  font-size: 1.5rem;
  line-height: 1.5rem;
```

2021-05-07 08:02 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.module.css
> +  margin-top: 30px;
Are you sure, that margin-top must be configured using `rem`?

2021-05-07 08:05 UTC, Dev1LtJ commented on src/components/Modals/Tasks/Task-helpers.js
> +              selectedUsers: newSelectedUsers,
Reduced

```suggestion
        if (prevState.data.selectedUsers.find((item) => item.id === action.name)) {
          state = {
            ...prevState,
            data: {
              ...prevState.data,
              selectedUsers: prevState.data.selectedUsers.filter((item) => item.id !== action.name),
            },
          };
```

2021-05-07 10:39 UTC, Dev1LtJ commented on src/components/Modals/CraftInput.module.css
> +  width: 45%;
Ok, i'll try to do my best.

2021-05-13 10:32 UTC, maximsan commented on src/components/Modals/Tasks/CreateTask.jsx
> +              type='date'
Actually it's not a good idea. In this case you break `single responsibility principle`.

2021-05-13 10:35 UTC, maximsan commented on src/utilities/internationalization.js
> +export const intDate = (date) => new Intl.DateTimeFormat('ru').format(new Date(date));
For me it means `integer date`. Be careful with naming it can be very confusing.

2021-05-13 10:38 UTC, maximsan approved these changes
It's approved. Good work.

2021-05-13 10:44 UTC, YauhenKoipish approved these changes

2021-05-13 10:48 UTC, merged