Week 4
Dev-incubator/DIMS.UI-14 pull request #28
Opened 2021-05-16 12:39 UTC by Dev1LtJ

Added following functions:
- view User Progress;
- view User Current Tasks (depends on User's role);
- full tracks managment (create, edit, delete).
All of these functions syncronize with database.

2021-05-16 16:04 UTC, maximsan requested changes
Hello! I left some notes. Please consider how you use `setState` method. Take attention on the other notes.

2021-05-16 16:04 UTC, maximsan commented on src/utilities/fb-helpers.js
> +      const { tracks } = tasks.find((item) => item.id === taskId);
I guess some of your methods can be also extracted to helpers, I see several repetitive places

2021-05-16 16:04 UTC, maximsan commented on src/utilities/form-validators.js
> +      validatorField = new Date(inputBody) > new Date(startDate);
it's better to create a helper method for this

2021-05-17 06:58 UTC, Dev1LtJ commented on package.json
> +    "firebase": "^8.6.1",
Okay, fixed.
```suggestion
  "dependencies": {
    "@testing-library/jest-dom": "5.12.0",
    "@testing-library/react": "11.2.6",
    "@testing-library/user-event": "13.1.9",
    "eslint": "7.26.0",
    "firebase": "8.6.1",
    "node-sass": "6.0.0",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "4.2.0",
    "react-router-dom": "5.2.0",
    "react-scripts": "4.0.3",
    "react-spinners": "0.10.6",
    "web-vitals": "1.1.2"
  },
  "devDependencies": {
    "codecov": "3.8.1",
    "commitizen": "4.2.4",
    "cz-conventional-changelog": "3.3.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "3.4.0",
    "husky": "6.0.0",
    "lint-staged": "10.5.4",
    "prettier": "2.2.1",
    "semantic-release": "17.3.9"
  },
```

2021-05-17 07:25 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +} from './Track-helpers';
Fixed in the whole project.

2021-05-17 07:26 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +export default class CreateTrack extends React.Component {
Fixed.
```suggestion
export default class CreateTrack extends React.PureComponent {
```

2021-05-17 07:29 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    }));
Okay, this will be my question on the meeting.
```suggestion
  componentDidMount() {
    const {
      task: { startDate, title },
    } = this.props;
    this.setState({ title, startDate });
  }
```

2021-05-17 07:31 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    }));
Fixed
```suggestion
    this.setState({ userId, taskId, taskData, tracks });
```

2021-05-17 07:38 UTC, Dev1LtJ commented on src/utilities/form-validators.js
> +      validatorField = new Date(inputBody) > new Date(startDate);
Completed!
```suggestion
    case 'date':
    case 'deadLine':
      validatorField = regExpDeadLineCheck(startDate, inputBody);
      errorField = validatorField ? '' : errors.deadLine;
      break;
```

2021-05-17 07:50 UTC, Dev1LtJ commented on src/components/Modals/Tracks/EditTrack.jsx
> +export default class EditTrack extends React.Component {
Fixed.
```suggestion
export default class EditTrack extends React.PureComponent {
```

2021-05-17 07:53 UTC, Dev1LtJ commented on src/pages/UsersProgress.jsx
> +      return <SimpleTrack tableIndex={index + 1} note={track.note} title={track.title} date={track.date} />;
oOps
```suggestion
        <SimpleTrack tableIndex={index + 1} key={track.id} note={track.note} title={track.title} date={track.date} />
```

2021-05-17 07:55 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    }));
Fixed.
```suggestion
    this.setState({ tracks });
```

2021-05-17 07:57 UTC, Dev1LtJ commented on src/pages/UsersProgress.jsx
> +    }));
Fixed
```suggestion
    this.setState({ allTracks, userName });
```

2021-05-17 08:01 UTC, Dev1LtJ commented on src/pages/UsersProgress.jsx
> +    const userName = `${user.data().username} ${user.data().surname}`;
Good idea!
```suggestion
    const userData = user.data();
    const { tasks, username, surname } = userData;
    const userFullName = `${username} ${surname}`;
```

2021-05-17 08:05 UTC, Dev1LtJ commented on src/components/Track/SimpleTrack.jsx
> +      <div>{internationalizeDate(date)}</div>
better case, i think: `getInternationalDate`. Fixed.

2021-05-17 08:13 UTC, Dev1LtJ commented on src/components/Track/Track-helpers.js
> +export const TRACK_MODAL_DELETE_TRACK = 'modal-track-delete';
Sure. Fixed in the whole project.
For this case:
```suggestion
export const TRACK_MODAL_DELETE_TRACK = 'TRACK_MODAL_DELETE_TRACK';
```

2021-05-17 08:18 UTC, Dev1LtJ commented on src/components/Task/UserTask.jsx
> +      <Button roleClass='delete' disabled={status === 'Failed'} onClick={handleFail}>
Fixed:
```suggestion
      <Button roleClass='delete' disabled={isFailed} onClick={handleFail}>
```

2021-05-17 08:19 UTC, Dev1LtJ commented on src/components/Task/UserTask.jsx
> +        {status === 'Active' ? 'Complete' : 'reActive'}
Fixed:
```suggestion
      <Button roleClass={isActive ? 'create' : null} onClick={handleComplete}>
        {isActive ? 'Complete' : 'reActive'}
      </Button>
```

2021-05-17 08:22 UTC, Dev1LtJ commented on src/components/Modals/Tracks/DeleteTrack.jsx
> +export default function DeleteTrack({ track, closeFunc, liftUpDeleteTrack }) {
I also need a track title:
`Are you really want to delete your track <span>{track.note}</span> from task <span>{track.title}</span> ?`

2021-05-17 11:02 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +  task: PropType.instanceOf(Object).isRequired,
Some details:
```suggestion
CreateTrack.propTypes = {
  task: PropType.shape({
    startDate: PropType.string,
    title: PropType.string,
  }).isRequired,
  closeFunc: PropType.func.isRequired,
  liftUpCreateTrack: PropType.func.isRequired,
};
```

2021-05-17 11:04 UTC, Dev1LtJ commented on src/components/Modals/Tracks/DeleteTrack.jsx
> +  track: PropType.instanceOf(Object).isRequired,
Fixed:
```suggestion
DeleteTrack.propTypes = {
  track: PropType.shape({
    note: PropType.string,
    title: PropType.string,
  }).isRequired,
  liftUpDeleteTrack: PropType.func.isRequired,
  closeFunc: PropType.func.isRequired,
};
```

2021-05-17 11:20 UTC, Dev1LtJ commented on src/pages/UsersTasks.jsx
> +    };
Moved to class method:
```suggestion
  selectActFunc(id, status) {
    const { isUser } = this.state;
    if (isUser) {
      noop();
    }

    this.changeStatus(id, status);
  }
```

2021-05-17 11:38 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    const openModal = () => this.toggleModal(TRACKS_MODAL_CREATE_TRACK);
Moved to class method:
```suggestion
  openModal = () => this.toggleModal(TRACKS_MODAL_CREATE_TRACK);
```

2021-05-17 12:18 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    this.setState(state, this.validateForm);
Discussed

2021-05-17 13:00 UTC, Dev1LtJ commented on src/components/Track/Track.jsx
> +    };
Moved to class method here and the whole document:
```suggestion
  selectActFunc() {
    const { selectedModal } = this.state;
    switch (selectedModal) {
      case TRACK_MODAL_DELETE_TRACK:
        return () => this.liftUpDeleteTrack();
      case TRACK_MODAL_EDIT_TRACK:
        return (editedTrack) => this.liftUpEditTrack(editedTrack);
      default:
        return () => noop;
    }
  }
```

2021-05-17 13:17 UTC, Dev1LtJ commented on src/components/Track/Track.jsx
> +    const trackCopy = { ...track, title, startDate };
Fixed.
```suggestion
    const extendedTrack = this.getExtendedTrack(track, title, startDate);
```

2021-05-17 13:38 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    const { tracks } = await user.data().tasks.find((item) => item.id === taskId);
Helper-method:
`export const getTracks = (user, taskId) => {
  return user.data().tasks.find((item) => item.id === taskId).tracks;
};`

```suggestion
    const tracks = getTracks(user, taskId);
```

2021-05-17 13:44 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    const { tracks } = await user.data().tasks.find((item) => item.id === taskId);
```suggestion
    const tracks = await getTracks(userId, taskId);
```
helper-method:
`export async function getTracks(userId, taskId) {
  const user = await getElementFromCollection(USERS, userId);
  const { tracks } = await user.data().tasks.find((item) => item.id === taskId);

  return tracks;
}`

2021-05-17 13:49 UTC, Dev1LtJ commented on src/pages/UsersTracks.jsx
> +    const { tracks } = await user.data().tasks.find((item) => item.id === taskId);
```suggestion
    const tracks = await getTracks(userId, taskId);
```

2021-05-17 13:58 UTC, Dev1LtJ commented on src/utilities/fb-helpers.js
> +      const { tracks } = tasks.find((item) => item.id === taskId);
```suggestion
      const tracks = getTracksWithoutRequest(tasks, taskId);
```

2021-05-17 22:12 UTC, Dev1LtJ commented on src/pages/UsersTasks.jsx
> +      );
Created several method.
```suggestion
    const tasksList = await getTasks(tasksWithStatus);
```

2021-05-18 07:45 UTC, Dev1LtJ commented on src/pages/UsersProgress.jsx
> +    }, []);
logic moved to service:
```suggestion
    const allTracks = await getAllTracksFromAllTasks(tasks);
```

2021-05-25 15:03 UTC, maximsan approved these changes

2021-05-25 15:28 UTC, YauhenKoipish approved these changes

2021-05-25 15:45 UTC, merged