Week 6
Dev-incubator/DIMS.UI-14 pull request #30
Opened 2021-05-30 19:14 UTC by Dev1LtJ

Created roles, google sign in button, password reset button. Rewritten many components.

2021-06-11 17:54 UTC, maximsan requested changes
Helooooo! I left several notes. Please review them carefully. Thanks for you work! Have a nice weekend! Please, keep me posted about your progress!

2021-06-11 17:54 UTC, maximsan commented on src/components/Routes.jsx
> +const userPermissions = [2, 3, 5, 6];
As I said it's bad approach, please change it, we should avoid using some kind of magic numbers, especially strange array of numbers.

2021-06-11 17:54 UTC, maximsan commented on src/components/Routes.jsx
> +  let permissionsList = null;
you can set it to `userPermissions` by default for example

2021-06-11 17:54 UTC, maximsan commented on src/components/Routes.jsx
> +  } else if (loggedUser.role === 'User') {
create `enum/dictionary` for `roles`, avoid using `string` values, because it introduces a lot of `manual` work if you decide to change something in the future

2021-06-11 17:54 UTC, maximsan commented on src/components/Routes.jsx
> +  }
you can re-write it with ternary operator to more short and nice code

2021-06-11 17:54 UTC, maximsan commented on src/components/Routes.jsx
> +  ));
`routePack` and this code looks almost identical, so you can create a reusable helper method for this. think how to do it. who knows maybe you will need `React.cloneElement` for this

2021-06-11 17:54 UTC, maximsan commented on src/pages/PageNotFound.jsx
> +  return <h2>Error 404</h2>;
nice 💯

2021-06-11 17:54 UTC, maximsan commented on src/pages/Users.jsx
> +    const isAdmin = role === 'Admin';
use `enum` here as I adviced

2021-06-11 17:54 UTC, maximsan commented on src/pages/UsersTasks.jsx
> +    const isUser = role === 'User';
you repeat it everywhere, think how mush manual work you will have to do if you decide to change a name

2021-06-11 17:54 UTC, maximsan commented on src/utilities/fb-helpers.js
> +    return error;
`Promise.reject(error)`

2021-06-12 06:50 UTC, Dev1LtJ commented on src/utilities/fb-helpers.js
> +    return error;
Fixed
```suggestion
    return Promise.reject(error);
```

2021-06-12 07:19 UTC, Dev1LtJ commented on src/components/Routes.jsx
> +const userPermissions = [2, 3, 5, 6];
According to your advice, it was perfectly reworked! Just look on it!
```suggestion
const paths = [
  { isExact: true, path: '/main/users', permissions: [ADMIN, MENTOR], component: UsersWithContext },
  { isExact: true, path: '/main/tasks', permissions: [ADMIN, MENTOR], component: Tasks },
  {
    isExact: true,
    path: '/main/users/:userId/tasks',
    permissions: [ADMIN, MENTOR, USER],
    component: UsersTasksWithContext,
  },
  {
    isExact: true,
    path: '/main/users/:userId/tasks/:taskId/track',
    permissions: [ADMIN, MENTOR, USER],
    component: UsersTracks,
  },
  { isExact: true, path: '/main/users/:userId/progress', permissions: [ADMIN, MENTOR], component: UsersProgress },
  { isExact: true, path: '/main/settings', permissions: [ADMIN, MENTOR, USER], component: SettingsWithContext },
  { isExact: false, path: '', permissions: [ADMIN, MENTOR, USER], component: PageNotFound },
];
```

2021-06-12 07:19 UTC, Dev1LtJ commented on src/components/Routes.jsx
> +  let permissionsList = null;
It was refactored according your previous task:
```suggestion
export const getRoleDependedRoutes = ({ role }) => {
  const rolePermissions = paths.filter((pathObj) => pathObj.permissions.includes(role));
  const routePack = rolePermissions.map((path) => (
    <Route key={Date.now().toString()} exact={path.isExact} path={path.path} component={path.component} />
  ));

  return <Switch>{routePack}</Switch>;
};
```

2021-06-12 07:20 UTC, Dev1LtJ commented on src/components/Routes.jsx
> +  } else if (loggedUser.role === 'User') {
Very good idea! I create `roles.js`:
`export const USER = 'User';
export const ADMIN = 'Admin';
export const MENTOR = 'Mentor';`

2021-06-12 07:40 UTC, Dev1LtJ commented on src/components/Routes.jsx
> +  }
it was perfectly updated:
```suggestion
export const getRoleDependedMenuLinks = ({ role }) => {
  const rolePermissionsLists = menuList.filter((menuObj) => menuObj.permissions.includes(role));

  return rolePermissionsLists.map((menuObj, index) => (
    <MenuItem key={index.toString()} title={menuObj.title} path={menuObj.path} image={menuObj.image} />
  ));
};
```

2021-06-12 07:41 UTC, Dev1LtJ commented on src/components/Routes.jsx
> +  ));
It's no needed, coz function was reworked (look up).

2021-06-12 07:42 UTC, Dev1LtJ commented on src/pages/Users.jsx
> +    const isAdmin = role === 'Admin';
yea, updated:
```suggestion
   const isAdmin = role === rolesPack.admin;
```

2021-06-12 07:43 UTC, Dev1LtJ commented on src/pages/UsersTasks.jsx
> +    const isUser = role === 'User';
updated:
```suggestion
    const isUser = role === rolesPack.user;
```

2021-06-12 10:33 UTC, Dev1LtJ commented on src/pages/PageNotFound.jsx
> +  return <h2>Error 404</h2>;
Created 404 page.

2021-06-13 10:02 UTC, maximsan requested changes
I left some comments. Good work! Let me now when everything will be ready for merging

2021-06-13 10:02 UTC, maximsan commented on src/components/Modals/Users/CreateUser.jsx
> +                options={`${admin}, ${mentor}, ${user}`}
pass already prepared array of options, do not pass this weird string

2021-06-13 10:02 UTC, maximsan commented on src/pages/Login.jsx
> +const { admin, mentor } = rolesPack;
don't spread it

2021-06-13 10:02 UTC, maximsan commented on src/utilities/rolesPack.js
> +const rolesPack = Object.freeze({
no need to freeze, it's extra work in this case

2021-06-13 10:16 UTC, Dev1LtJ commented on src/pages/Login.jsx
> +  } else if (role === mentor) {
Refactored: `ROLES.ADMIN, ROLES.ADMIN` and etc.

2021-06-13 10:16 UTC, Dev1LtJ commented on src/components/Modals/Users/CreateUser.jsx
> +                options={`${admin}, ${mentor}, ${user}`}
Completed: `options={[ROLES.ADMIN, ROLES.MENTOR, ROLES.USER]}`

2021-06-13 10:17 UTC, Dev1LtJ commented on src/pages/Login.jsx
> +const { admin, mentor } = rolesPack;
Removed.

2021-06-13 10:17 UTC, Dev1LtJ commented on src/utilities/rolesPack.js
> +const rolesPack = Object.freeze({
Refactored to: `const ROLES = {
  USER: 'User',
  ADMIN: 'Admin',
  MENTOR: 'Mentor',
};`

2021-06-14 07:25 UTC, YauhenKoipish approved these changes

2021-06-15 18:06 UTC, maximsan approved these changes
Hello, please use enums!

2021-06-15 18:06 UTC, maximsan commented on src/components/Modals/Users/CreateUser.jsx
> +        sex: 'Male',
use enum here too

2021-06-15 18:06 UTC, maximsan commented on src/components/Modals/Users/CreateUser.jsx
> +                options={['Male', 'Female']}
use enum here

2021-06-15 18:07 UTC, merged