Week 7
Dev-incubator/DIMS.UI-14 pull request #35
Opened 2021-06-03 10:49 UTC by Dev1LtJ

Created ThemeContext with dark and light theme based on CSS-Variables.

2021-06-15 21:34 UTC, maximsan requested changes
I left some notes. Please review them and try to fix. Good refactoring. Thanks!

2021-06-15 21:34 UTC, maximsan commented on src/App/App.jsx
> +    applyGlobalTheme(theme);
why is it here ? it should be in life cycle methods

2021-06-15 21:34 UTC, maximsan commented on src/App/App.jsx
> +  };
Actually, why do you hold all context's methods in the App ?  Create you custom Provider component and place them there. you don't need them in App, in constructor

2021-06-15 21:34 UTC, maximsan commented on src/index.css
> +  --modal-background-color: #fff;
it looks odd. create css variables for the same colors in root and then call it here like`--modal-background-color: var(--white);` follow DRY principle

2021-06-15 21:34 UTC, maximsan commented on src/pages/Settings.jsx
> +            onClick={this.selectDarkTheme}
create a component, you have the same peace of code twice

2021-06-15 21:34 UTC, maximsan commented on src/utilities/context-helpers.js
> +export const THEME_DARK = 'dark';
Why did you not create enum for theme too ?

2021-06-16 07:13 UTC, Dev1LtJ commented on src/utilities/context-helpers.js
> +export const THEME_DARK = 'dark';
Created:
```suggestion
export const THEMES = {
  THEME: 'theme',
  LIGHT: 'light',
  DARK: 'dark',
};
```

2021-06-16 10:20 UTC, Dev1LtJ commented on src/pages/Settings.jsx
> +            onClick={this.selectDarkTheme}
Created: 
```suggestion
const ThemeButton = ({ children, onClick, isActive }) => {
  const classList = isActive ? `${classes.item} ${classes.active}` : `${classes.item}`;

  return (
    <button type='button' onClick={onClick} className={classList}>
      <span>{children}</span>
      <img className={classes.img} src={children === THEMES.DARK ? moonLogo : sunLogo} alt='themeButton-logo' />
    </button>
  );
};
```

2021-06-16 11:10 UTC, Dev1LtJ commented on src/index.css
> +  --modal-background-color: #fff;
Created: 
```suggestion
:root {
  --white: #fff;
  --black: #000;
  --backgroundGray: #f6f7fb;
  --lightGray: #ecedf1;
  --darkGray: #7787ab;
  --darkBlue: #0e1935;
  --navyBlue: #122043;
  --lightBlue: #5385ff;
  --skyBlue: #3855a5;
  --red: #d50000;
  --darkRed: #ae0000;
  --wineRed: #500000;
  --crimeRed: #8b0000;
  --lightOrange: #ffa610;
  --orange: #ff7518;
  --darkOrange: #894b00;
  --pumpkinOrange: #c46c00;
  --lightGreen: #1bc47d;
  --green: #0ca52f;
  --darkGreen: #026c45;
  --slytherinGreen: #013220;
}
```

2021-06-17 17:44 UTC, Dev1LtJ commented on src/App/App.jsx
> +  };
Moved to:
1) ComponentDidMount
2) ComponentDidUpdate

2021-06-17 17:45 UTC, Dev1LtJ commented on src/App/App.jsx
> +    applyGlobalTheme(theme);
Moved to:
1) ComponentDidMount;
2) ComponentDidUpdate.

2021-06-18 07:02 UTC, maximsan approved these changes
Looks fine! Good job. Approved!

2021-06-18 08:11 UTC, YauhenKoipish approved these changes

2021-06-18 13:14 UTC, merged