Week 8
Dev-incubator/DIMS.UI-14 pull request #36
Opened 2021-06-21 20:59 UTC by Dev1LtJ

Updates: 
- Created about page;
- Created README.MD using Readme-md-generator;
- Created Context Consumers for App and Login pages;
- Common pages have rewritten using Redux connect (React Contexts were saved for demonstration);
- Routing was rewritten.
- Small refactoring and a bit of fixes.

2021-06-22 12:26 UTC, maximsan requested changes
Hello! I Left some minor notes. Review your logic in `connectors`. I see that you can create some helper methods and reduce duplication. Code will be cleaner. Anyway it's a good work!

2021-06-22 12:26 UTC, maximsan commented on src/components/Homepage/About/Feature.jsx
> +  img: PropTypes.instanceOf(Object).isRequired,
Is it object ? I guess it should be a string(url)

2021-06-22 12:26 UTC, maximsan commented on src/components/Homepage/About/Feature.module.css
> +  flex-direction: row-reverse;
try to avoid using of this approach, is it possible to reverse data in other way ?

2021-06-22 12:26 UTC, maximsan commented on src/components/Loader/Loader.jsx
> +      size={50}
use size and color as props

2021-06-22 12:26 UTC, maximsan commented on src/pages/About.jsx
> +import reduxImg from '../images/redux.svg';
import all images to one file and export them from it

2021-06-22 12:26 UTC, maximsan commented on src/utilities/fb-helpers.js
> +// unused with Redux (UsersTasks Page)
Maybe let's delete the methods if we don't use them anymore ?

2021-06-22 12:26 UTC, maximsan commented on src/pages/UsersProgress.jsx
> +    const { title } = state.tasks.tasksList.find((task) => task.id === taskWithTrack.id);
create a helper method `getTrackTitleById`

2021-06-22 12:26 UTC, maximsan commented on src/pages/UsersTasks.jsx
> +  const userFullName = `${userData.username} ${userData.surname}`;
create helper method `createUserFullName`

2021-06-22 12:26 UTC, maximsan commented on src/pages/UsersTasks.jsx
> +  );
create helper method

2021-06-23 06:30 UTC, Dev1LtJ commented on src/components/Loader/Loader.jsx
> +      size={50}
Fixed:
```suggestion
const Loader = ({ color, size }) => {
  return (
    <HashLoader
      color={color}
      css='display: block; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);'
      size={size}
    />
  );
};

export default Loader;

Loader.propTypes = {
  color: PropTypes.string,
  size: PropTypes.number,
};

Loader.defaultProps = {
  color: '#5385ff',
  size: 50,
};
```

2021-06-23 07:29 UTC, Dev1LtJ commented on package.json
> +    "readme-md-generator": "^1.0.0",
Package has been uninstalled:
```suggestion
      "dependencies": {
    "@testing-library/jest-dom": "5.12.0",
    "@testing-library/react": "11.2.6",
    "@testing-library/user-event": "13.1.9",
    "axios": "^0.21.1",
    "eslint": "7.26.0",
    "firebase": "8.6.1",
    "node-sass": "6.0.0",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "4.2.0",
    "react-redux": "^7.2.4",
    "react-router-dom": "5.2.0",
    "react-scripts": "4.0.3",
    "react-spinners": "0.10.6",
    "redux": "^4.1.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.3.0",
    "web-vitals": "1.1.2"
  },
```

2021-06-23 07:31 UTC, Dev1LtJ commented on src/utilities/fb-helpers.js
> +// unused with Redux (UsersTasks Page)
Deleted 2 methods.

2021-06-23 07:49 UTC, Dev1LtJ commented on src/components/Aside/Aside.jsx
> +};
It's brilliant!
```suggestion
export default connect(({ menu: { isOpen } }) => ({ isOpen }), null)(Aside);
```

2021-06-23 07:52 UTC, Dev1LtJ commented on src/App/App.jsx
> +  loggedUser: PropTypes.instanceOf(Object).isRequired,
loggedUser object has more fields, but i shaped only necessary: 
```suggestion
App.propTypes = {
  isLogged: PropTypes.bool.isRequired,
  loggedUser: PropTypes.shape({
    id: PropTypes.string.isRequired,
    role: PropTypes.string.isRequired,
  }).isRequired,
};
```

2021-06-23 08:32 UTC, Dev1LtJ commented on src/pages/About.jsx
> +import reduxImg from '../images/redux.svg';
Created about-helpers.jsx:
```suggestion
import { RiAdminFill } from 'react-icons/ri';
import { FaUserAlt, FaUserGraduate } from 'react-icons/fa';
import loginImg from '../images/Login.png';
import usersImg from '../images/users.png';
import tasksImg from '../images/tasks.png';
import manageTasksImg from '../images/UsersTasks.png';
import progressImg from '../images/Progress.png';
import currentTasks from '../images/currentTasks.png';
import tracksImg from '../images/Tracks.png';
import html5 from '../images/html5.svg';
import css3 from '../images/css3.svg';
import js from '../images/js.svg';
import reactImg from '../images/react.svg';
import firebaseImg from '../images/firebase.svg';
import reduxImg from '../images/redux.svg';

export const features = [
  {
    img: loginImg,
    title: 'Login System',
    descr:
      'App provides login page for your account according to your credentials. Also you can login with Google Authentication.',
  },
  {
    img: usersImg,
    title: 'Manage Users',
    descr: 'You can manage your users: create users, including fields validation, edit and delete current users.',
  },
  {
    img: tasksImg,
    title: 'Manage Tasks',
    descr:
      'You can manage your tasks: create tasks, including fields validation, assign tasks to users, edit and delete tasks.',
  },
  {
    img: manageTasksImg,
    title: 'Control Users Tasks Completion',
    descr: 'You can set task status: complete, fail, active/reactive tasks users has been assigned.',
  },
  {
    img: progressImg,
    title: 'View Progress',
    descr: 'You can view progress of each included user.',
  },
  {
    img: currentTasks,
    title: 'View Tasks Assigned to You',
    descr: "You can view assigned tasks, every task's status, task name, start date and deadline.",
  },
  {
    img: tracksImg,
    title: 'Manage Tracks',
    descr: 'You can manage your task tracks: create, edit and delete.',
  },
];

export const roles = [
  {
    title: 'Admin',
    img: <RiAdminFill />,
    list: [
      'Watch the User&apos;s Manage Grid',
      "Add, edit and delete a User on User's Manage Grid",
      "Watch the User's Progress Grid",
      'Watch the Tasks Manage Grid',
      'Add, edit and delete Tasks',
      "Watch the User's Task Manage Grid",
      "Set the User's Task's Status",
    ],
  },
  {
    title: 'Mentor',
    img: <FaUserGraduate />,
    list: [
      "Watch the User's Manage Grid",
      "Watch the User's Progress Grid",
      'Watch the Tasks Manage Grid',
      'Add, edit and delete Tasks',
      "Watch the User's Task Manage Grid",
      "Set the User's Task's Status",
    ],
  },
  {
    title: 'User',
    img: <FaUserAlt />,
    list: [
      'Watch the Tasks Manage Grid',
      'Watch the Tracks Manage Grid of the current Task',
      'Add, edit and delete a Tracks of the current Task',
    ],
  },
];

export const techs = [
  {
    title: 'HTLM5',
    img: html5,
    descr: 'Creates a structure of an App. The fifth version allow to created more SEO-optimized structure.',
  },
  {
    title: 'CSS3',
    img: css3,
    descr: 'It helps to create absolutely any appearance of an App. Everything is limited of your fantasy.',
  },
  {
    title: 'JavaScript',
    img: js,
    descr: 'Allows to create any logic of an App: manage data, receiving and posting data from the server, etc.',
  },
  {
    title: 'React',
    img: reactImg,
    descr: 'This library helps to create web-SPA. The most interactive App for your goals can be created with it.',
  },
  {
    title: 'Firebase',
    img: firebaseImg,
    descr: "It's noSQL database, which stores data of an App. Also firebase can be user for authentication.",
  },
  {
    title: 'Redux',
    img: reduxImg,
    descr: "It's a predictable state container for JS Apps. Allow you to easy manage an App's state.",
  },
];

```

2021-06-23 08:46 UTC, Dev1LtJ commented on src/components/Homepage/About/Feature.jsx
> +  img: PropTypes.instanceOf(Object).isRequired,
It is strange, but you're right....

```suggestion
Feature.propTypes = {
  img: PropTypes.string,
  title: PropTypes.string,
  descr: PropTypes.string,
  reversed: PropTypes.bool,
};

Feature.defaultProps = {
  img: '',
  title: '',
  descr: '',
  reversed: false,
};
```

2021-06-23 23:40 UTC, Dev1LtJ commented on src/pages/UsersTasks.jsx
> +  const userFullName = `${userData.username} ${userData.surname}`;
Fixed:
```suggestion
  const userFullName = createUserFullName(userData);
```

2021-06-23 23:41 UTC, Dev1LtJ commented on src/pages/UsersProgress.jsx
> +    const { title } = state.tasks.tasksList.find((task) => task.id === taskWithTrack.id);
```suggestion
  const allTracks = getAllTracksWithTaskTitle(state, userData);
```

2021-06-23 23:44 UTC, Dev1LtJ commented on src/pages/UsersTasks.jsx
> +  );
```suggestion
  const tasksList = getUserTasks(state, userData);
```

2021-06-23 23:52 UTC, Dev1LtJ commented on src/components/Homepage/About/Feature.module.css
> +  flex-direction: row-reverse;
Fixed with blocks replacing.

2021-06-24 07:22 UTC, YauhenKoipish approved these changes

2021-06-24 11:52 UTC, maximsan approved these changes
Looks good!

2021-06-24 11:52 UTC, merged