Week 9
Dev-incubator/DIMS.UI-14 pull request #37
Opened 2021-06-28 19:12 UTC by Dev1LtJ

Changes:
- refresh-page fetching usersList and tasksList from firebase was hoisted to "Main" Component;
- refresh-page fetching was rewritten using React & React-Redux Hooks;
- two packages of custom Hooks was created using React Hooks for training;
- Modals: CreateTrack, EditTrack, CreateTask, EditTask, CreateUser, EditUser were rewritten using hand-crafted Hooks (CreateTrack, EditTrack, CreateUser, EditUser with first package of custom Hooks, as well as CreateTask, EditTask with second package of custom Hooks);
- unnecessary now helpers were deleted.

2021-06-29 16:20 UTC, maximsan requested changes
Hello! I left some comments. Let me know if you have questions. Good work!

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tasks/EditTask.jsx
> +      firstRender.current = false;
why do you need it ? it looks like your implementation is wrong if you need this in your case

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tasks/EditTask.jsx
> +  }, [state.title, state.startDate, state.deadLine, state.selectedUsers]);
Dependencies array should contains only used parameters. That is wrong

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tasks/EditTask.jsx
> +          <Button onClick={() => closeFunc()}>Close</Button>
create a method

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    id: createElemRefOnDB(TRACKS).id,
looks like your method can be called outside of the component and you will avoid extra work

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    undefined,
it's a sign that your method API is bad

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/Tracks/CreateTrack.jsx
> +          <Button onClick={() => closeFunc()}>Close</Button>
create a method

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +        const validity = !!action.payload.state.selectedUsers.length;
what does the name mean ? it's bad name from my point of view, you should rename it

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +      return prevState;
why do you need this return ? I guess it is redundant

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +      if (action.payload.event.name in prevState.validator) {
hm, I don't like this approach. can we rework it ?

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +        if (prevState.selectedUsers.find((id) => id === action.payload.name)) {
save result in a variable before this

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +      if (action.payload.type === 'checkbox') {
I'd suggest to do payload destructiring here

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +  console.log(state);
remove

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +  const onChange = ({ target: { name, value } }) =>
wrap in useCallback

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +    console.log(errors);
remove

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +export const useValidator = (initialState, password = '', startDate = '', ...trackedFields) => {
use an object for parameters in this case

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +  const [state, setState] = useState(() => initialState);
I'd suggest you to move lazy loading in place where you call custom hook and do check if it's function or an object and then call or not

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +  const [isValid, setIsValid] = useState(() => false);
it doesn't make sense, set false

2021-06-29 16:20 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +    const changedField = trackedFields.find((field, index) => field[1] !== prevTrackedFieldsRef.current[index][1]);
don't use magic numbers, create a helper for this and cover with unit tests

2021-07-02 06:43 UTC, Dev1LtJ commented on src/components/Main/Main.jsx
> +  }, [dispatch]);
Fixed:
```suggestion
  useEffect(() => {
    dispatch(fetchUsers());
    dispatch(fetchTasks());
  }, [dispatch]);
```

2021-07-02 06:44 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +  const onChangeSnapshot = useRef({});
Fixed:
```suggestion
  const onChangeSnapshotRef = useRef({});
```

2021-07-02 06:48 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +  const [state, dispatchState] = useReducer(stateReducer, newTaskRef.current.id, (newTaskId) => ({
According to useReducer specification, newTaskId (parameter of initializer) comes from newTaskRef.current.id (initialize value). newTaskRef.current is the reference (!), created in the firebase by the method: createElemRefOnDB(TASKS):
`export const createElemRefOnDB = (collection) => db.collection(collection).doc();`

2021-07-02 06:53 UTC, Dev1LtJ commented on src/components/Modals/Tasks/EditTask.jsx
> +          <Button onClick={() => closeFunc()}>Close</Button>
Fixed:
```suggestion
          <Button onClick={closeModal}>Close</Button>
```

2021-07-02 06:57 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +          <Button onClick={() => closeFunc()}>Close</Button>
```suggestion
          <Button onClick={closeFunc}>Close</Button>
```

2021-07-02 07:00 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +      return prevState;
As we have discussed this case on the meeting, arrow function requires return.

2021-07-02 07:02 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  console.log(state);
Removed:
```suggestion

```

2021-07-02 07:03 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +    console.log(errors);
Removed:
```suggestion

```

2021-07-02 07:04 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  const [isValid, setIsValid] = useState(() => false);
fixed:
```suggestion
  const [isValid, setIsValid] = useState(false);
```

2021-07-02 07:10 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  const [state, setState] = useState(() => initialState);
Fixed:
```suggestion
const [state, setState] = useState(typeof initialState === 'function' ? initialState() : initialState);
```

2021-07-02 07:15 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  const onChange = ({ target: { name, value } }) =>
Wrapped:

```suggestion
  const onChange = useCallback(
    ({ target: { name, value } }) =>
      setState((prevState) => {
        return {
          ...prevState,
          [name]: value,
        };
      }),
    [],
  );
```

2021-07-02 07:19 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    id: createElemRefOnDB(TRACKS).id,
I created a ref: ` const newTrackRef = useRef(createElemRefOnDB(TRACKS));`
```suggestion
  const { state, onChange } = useInput(() => ({
    id: newTrackRef.current.id,
    name: '',
    date: '',
    note: '',
  }));
```

2021-07-02 08:00 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +      if (action.payload.type === 'checkbox') {
Rewritten:
```suggestion
export const stateReducer = (prevState, action) => {
  const {
    payload: { name, value, type },
  } = action;

  switch (action.type) {
    case TASK_ONCHANGE:
      if (type === 'checkbox') {
        if (prevState.selectedUsers.find((id) => id === name)) {
          return {
            ...prevState,
            selectedUsers: prevState.selectedUsers.filter((id) => id !== name),
          };
        }
```

2021-07-04 07:58 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +export const useValidator = (initialState, password = '', startDate = '', ...trackedFields) => {
Reworked:
```suggestion
export const useValidator = (initialState, password = '', startDate = '', trackedFields) => {
```

2021-07-04 07:59 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +    const changedField = trackedFields.find((field, index) => field[1] !== prevTrackedFieldsRef.current[index][1]);
Created:
```suggestion
    const changedField = findChangedField(prevTrackedFieldsRef.current, trackedFields);
```

2021-07-04 08:01 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +        const validity = !!action.payload.state.selectedUsers.length;
Fixed:
```suggestion
        const isValid = !!action.payload.state.selectedUsers.length;
        const errorMsg = isValid ? '' : 'At least one user must be selected';
```

2021-07-05 08:46 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +        if (prevState.selectedUsers.find((id) => id === action.payload.name)) {
Saved:
```suggestion
        const isSelectedUserExists = prevState.selectedUsers.find((id) => id === name);
        if (isSelectedUserExists) {
```

2021-07-05 08:47 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +      if (action.payload.event.name in prevState.validator) {
Reworked: created method for search: `const isFieldNameInValidator = Object.keys(prevState.validator).includes(name);`
So:
```suggestion
      if (isFieldNameInValidator) {
```

2021-07-05 10:38 UTC, Dev1LtJ commented on src/components/Modals/Tasks/EditTask.jsx
> +      firstRender.current = false;
Reworked with creating custom hook:
```suggestion
export const useAllSelectedFormsValidityChecker = (validator, initialState) => {
  const [isValid, setIsValid] = useState(false);
  const initialStateRef = useRef(initialState);

  const isOneOfStateFieldsChanged = useMemo(() => checkIfOneOfFieldsChanged(initialStateRef.current, initialState), [
    initialStateRef.current,
    initialState,
  ]);
  useEffect(() => {
    if (isOneOfStateFieldsChanged) {
      console.log('useEffect setIsValid');
      setIsValid(checkAllFormValidity(validator));
    }
  }, [validator, isOneOfStateFieldsChanged]);

  return isValid;
};
```

2021-07-05 12:27 UTC, Dev1LtJ commented on src/components/Modals/Tasks/EditTask.jsx
> +  }, [state.title, state.startDate, state.deadLine, state.selectedUsers]);
Fixed:
```suggestion
  useEffect(() => {
    dispatchValidator({ type: TASK_VALIDATE, payload: { state, event: onChangeSnapshotRef.current } });
    /*
     I don't need other dependencies here, coz validator's reducer has a checker, which verifies,
      event-changed field inside or outside validator and returns prevState.
    */
  }, [state]);
```

2021-07-06 07:04 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +    undefined,
Reworked

2021-07-06 16:10 UTC, maximsan requested changes
Hello! Left some comments. Please review, let me know fi you have questions. Thanks! Good try :) It's almost better than good )

2021-07-06 16:10 UTC, maximsan commented on src/components/Modals/modals-helpers.js
> +        return useValidator(initialState, password, startDate, trackedFields);
now it looks scary. just use wrapper with default values for unnecessary fields

2021-07-06 16:10 UTC, maximsan commented on src/utilities/form-helpers.js
> +  return newObjEntries.find((field, index) => field[1] !== prevObjEntries[index][1]);
add explanation about why we use this approach and why we use [1] in first and second object

2021-07-06 16:10 UTC, maximsan commented on src/components/Modals/Tracks/CreateTrack.jsx
> +  }))()(startDate)(useMemo(() => ({ name: state.name, date: state.date }), [state.name, state.date]));
@Dev1LtJ  I don't see any real reason to use `useMemo` here and in other cases, just pass values. That should be fine. But actually I left in this hook that it's better to rewrite it. it looks scary :) it should be covered by unit-tests ^-^

2021-07-06 16:41 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +    initialStateRef.current,
Removed
```suggestion

```

2021-07-06 16:43 UTC, Dev1LtJ commented on src/utilities/form-helpers.js
> +  return newObjEntries.find((field, index) => field[1] !== prevObjEntries[index][1]);
Added:
```suggestion
export const findChangedField = (prevObj, newObj) => {
  const prevObjEntries = Object.entries(prevObj);
  const newObjEntries = Object.entries(newObj);
  // it's a method to safe comparing two objects. [1] - it is the value.
  return newObjEntries.find((field, index) => field[1] !== prevObjEntries[index][1]);
};
```

2021-07-06 16:48 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +        <div className={classes.requiredwarning}>* - these fields are required.</div>
Fixed: 
```suggestion
        <div className={classes.requiredWarning}>* - these fields are required.</div>
```

2021-07-06 16:59 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  });
Created helper:
```suggestion
  const [errors, setErrors] = useState(() => createErrorsStateByValidator(validator));
```
Also covered by tests.

2021-07-07 07:22 UTC, Dev1LtJ commented on src/components/Modals/Tasks/CreateTask.jsx
> +  const [validator, dispatchValidator] = useReducer(validatorReducer, undefined, () => ({
```suggestion
  const [{ validator, errors }, dispatchValidator] = useReducer(validatorReducer, undefined, () => ({
```

2021-07-07 07:48 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +        return useValidator(initialState, password, startDate, trackedFields);
Deleted.
```suggestion

```

2021-07-07 08:16 UTC, Dev1LtJ commented on src/components/Modals/Tracks/CreateTrack.jsx
> +  }))()(startDate)(useMemo(() => ({ name: state.name, date: state.date }), [state.name, state.date]));
Rewrited:
```suggestion
  const { errors, validator } = useValidator(
    () => ({
      name: false,
      date: false,
    }),
    undefined,
    startDate,
    { name: state.name, date: state.date },
  );
```

2021-07-07 08:57 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +      console.log('useEffect setIsValid');
removed

2021-07-07 08:57 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +      console.log('useEffect setValidator, setErrors');
removed

2021-07-07 08:57 UTC, Dev1LtJ commented on src/components/Modals/modals-helpers.js
> +  console.log('onChange');
removed

2021-07-08 22:29 UTC, maximsan approved these changes
Looks fine. Congratulations!

2021-07-12 07:23 UTC, YauhenKoipish approved these changes

2021-07-13 14:28 UTC, merged